apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    # Rule 1: Normal Web Browser Traffic
    - kind: Rule
      match: Host(`argocd.anuj`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    # Rule 2: Argo CD CLI (gRPC) Traffic
    - kind: Rule
      match: Host(`argocd.anuj`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls: {} 
