apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: '10.*' 
    chart: argo-cd
    helm:
      values: |
        server:
          ingress:
            enabled: true
            ingressClassName: tailscale
            hosts:
              - argocd.snapper-larch.ts.net
            tls:
              - hosts:
                - argocd.snapper-larch.ts.net
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/anujj14/homelab.git'
    path: cluster 
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default # All apps will deploy to the default namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
