# Disable components that K3s bundles internally
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false

grafana:
  ingress:
    enabled: true
    ingressClassName: tailscale
    hosts:
      - grafana
    tls:
      - hosts:
          - grafana
